use db;
-- Departments table
CREATE TABLE DEPT_INFO (
  DEPT_ID INT NOT NULL PRIMARY KEY,
  DEPT_NAME VARCHAR(100) NOT NULL
);

-- Employees table
CREATE TABLE EMP_INFO (
  EMP_ID INT  NOT NULL PRIMARY KEY,
  EMP_NAME VARCHAR(100) NOT NULL,
  EMP_SALARY DECIMAL(12,2) NOT NULL,
  DEPT_ID INT,
  CONSTRAINT fk_emp_dept FOREIGN KEY (DEPT_ID) REFERENCES DEPT_INFO(DEPT_ID)
    ON DELETE SET NULL
    ON UPDATE CASCADE
);


INSERT INTO DEPT_INFO (DEPT_ID, DEPT_NAME) VALUES
(101, 'SALES'),
(102, 'FINANCE'),
(103, 'MARKETING'),
(104, 'IT'),
(105, 'HR');

-- Insert 5 records into EMP_INFO
INSERT INTO EMP_INFO (EMP_ID, EMP_NAME, EMP_SALARY, DEPT_ID) VALUES
(1, 'JOHN',   45000.00, 101),
(2, 'SHAM',   65000.00, 104),
(3, 'RAJ',    78000.00, 103),
(4, 'ANKITA',120000.00, 101),
(5, 'DAVID',  52000.00, 105);

select * from EMP_INFO;
SELECT * FROM DEPT_INFO;

-- INNER JOIN  
SELECT 
    EMP_INFO.EMP_ID,                  
    EMP_INFO.EMP_NAME,
    EMP_INFO.EMP_SALARY,
    EMP_INFO.DEPT_ID,
    DEPT_INFO.DEPT_NAME
FROM EMP_INFO
INNER JOIN DEPT_INFO
ON EMP_INFO.DEPT_ID = DEPT_INFO.DEPT_ID;

-- INNER JOIN MADAM QUERY 
SELECT EMP_INFO.EMP_ID,  EMP_INFO.EMP_NAME,  EMP_INFO.EMP_SALARY,  EMP_INFO.DEPT_ID
FROM EMP_INFO
INNER JOIN DEPT_INFO
ON EMP_INFO.DEPT_ID =DEPT_INFO.DEPT_ID;

-- LEFT JOIN
SELECT 
    e.EMP_ID,
    e.EMP_NAME,
    e.EMP_SALARY,
    e.DEPT_ID,
    d.DEPT_NAME
FROM EMP_INFO e
LEFT JOIN DEPT_INFO d
ON e.DEPT_ID = d.DEPT_ID;

-- LEFT JOIN MADAM QUERY
SELECT
    EMP_INFO.EMP_ID,
    EMP_INFO.EMP_NAME,
    EMP_INFO.EMP_SALARY,
    DEPT_INFO.DEPT_NAME
FROM EMP_INFO
LEFT JOIN DEPT_INFO
ON EMP_INFO.DEPT_ID = DEPT_INFO.DEPT_ID;


