use db;
DELIMITER //
CREATE TRIGGER BEFORE_INSERT_EMPLOYEE
BEFORE INSERT ON employees
FOR EACH ROW 
BEGIN 
    IF NEW.SALARY< 0 THEN
       SET NEW.SALARY=0;
	END IF;
END//

SELECT * FROM EMPLOYEES;
CREATE TABLE EMPLOYEE_AUDIT(EMP_ID INT PRIMARY KEY, ACTION_TYPE VARCHAR(50), ACTION_DATE DATE);




